### ISSUE TITLE
how can i use it to do text summarization?

### ISSUE THREAD

**Issue by loongriver** [takase/control-length#1]
can author give an example to show how to do text_sum

**Comment by takase** [comment]
The description is here: https://github.com/takase/control-length/tree/master/encdec
Your question means you need more details?

**Comment by loongriver** [comment]
yes,I don't quite understand what's going on

**Comment by takase** [comment]
I think you can reproduce our results based on the description: https://github.com/takase/control-length/tree/master/encdec
If you have not run fairseq, description in fairseq (https://github.com/pytorch/fairseq/tree/master/examples/translation) might help because our code is based on fairseq.
If you have any question, can you tell me the details of the question.

**Comment by prince12th** [comment]
Maybe you can provide more details about the format of input data

**Comment by takase** [comment]
Sorry for late reply.
I add format of an input data: https://github.com/takase/control-length/tree/master/encdec .
Actually, my code regards plain text as an input for pre-processing script in the same as [fairseq](https://github.com/pytorch/fairseq).
